name: Deploy

on:
  release:
    types: [created]

jobs:
  deploypypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    env:
      PREFIX: /usr 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        sudo git clone https://github.com/pylover/python-makelib.git /usr/local/lib/python-makelib
        make install-common editable-install
    - name: Create distributions
      run: make dist
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.9
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
