name: PyPI

on:
  release:
    types: [created]

jobs:
  pypi:
    name: PyPI
    runs-on: ubuntu-latest
    env:
      VENVPATH: /usr 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: make env-ci
    - name: Create distributions
      run: make dist
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.9
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}

